Refactor authentication flow to integrate `rn-module-spotify-client` and enhance API handling
- Replaced `react-native-app-auth` with `rn-module-spotify-client` for managing Spotify authentication, updating related methods and interfaces.
- Introduced `AuthResult` sealed class in Kotlin for better error and result handling during authentication.
- Enhanced `DefaultAuthClient` by utilizing `rn-module-spotify-client` for authorization flow, updating `buildAuthConfig` accordingly.
- Updated `yarn.lock` and `rn-lib/package.json` to reflect the inclusion of `rn-module-spotify-client` as a dependency.
- Refactored `SpotifyBridge` for improved token-related logic, added timeout handling with `awaitTokenOrNull`, and integrated error-handling mechanisms.

diff --git a/lefthook.yml b/lefthook.yml
--- a/lefthook.yml
+++ b/lefthook.yml
@@ -10,9 +10,15 @@ pre-commit:
             glob: "*.{kt,kts}"
 
         # ---- Ktlint ----
+
+        ktlintFormat:
+            glob: "*.kt"
+            run: echo "\033[0;34m🔍 Running Ktlint Format...\033[0m" && ./gradlew ktlintFormat -x spotlessKotlin -x spotlessKotlinGradle || { echo "\033[0;31m❌ Ktlint Format FAILED!\033[0m" >&2; exit 1; }
+
         ktlint:
             glob: "*.kt"
             run: echo "\033[0;34m🔍 Running Ktlint checks...\033[0m" && ./gradlew ktlintCheck -x spotlessKotlin -x spotlessKotlinGradle || { echo "\033[0;31m❌ Ktlint checks FAILED!\033[0m" >&2; exit 1; }
+
 
         # ---- Prettier (TypeScript/JavaScript formatting) ----
         prettier:
